spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-flyway?autoReconnect=true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Tokyo
