package com.example.book.domain.entity;

/**
 * 自動生成されるIDを管理するインターフェース
 *
 * @author YutaMori
 */
public interface AutoGeneratedIdManageable {

    /**
     * IDを取得するメソッド
     */
    String getAutoGeneratedId();

    /**
     * IDを設定するメソッド
     *
     * @param id ID
     */
    void setAutoGeneratedId(String id);

}
